language: android
jdk:
    - oraclejdk8

sudo: false

cache:
  directories:
  - $HOME/.gradle/caches/

env:
  global:
    MALLOC_ARENA_MAX=2
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.3
    - build-tools-28.0.3
    - android-19
    - android-24
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19
    
before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo d56f5187479451eabf01fb78af6dfcb131a6481e > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo 24333f8a63b6825ea9c5514f83c2829b004d1fee >> "$ANDROID_HOME/licenses/android-sdk-license"
  
before_script:
    - export "JAVA_OPTS=-Xmx1024m"
    - export "JAVA7_HOME=/usr/lib/jvm/java-7-oracle"
    - export "JAVA8_HOME=/usr/lib/jvm/java-8-oracle"
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI --skin WVGA800
    - ./gradlew :app:assembleDebug
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script:
    - ./gradlew :daggermockTests:test :daggermockTests:codeCoverageReport --stacktrace
    - bash <(curl -s https://codecov.io/bash)
    - ./gradlew testDebugUnitTest :app:connectedAndroidTest --stacktrace
